#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## Set GTK Themes, Icons, Cursor and Fonts
## Edited by @yurihikari

THEME='Catppuccin-Macchiato-Standard-Lavender-Dark'
ICONS='Tela-circle-purple-dark'
FONT='Noto Sans 10'
CURSOR='Catppuccin-Macchiato-Mauve'
CURSOR_SIZE='32'

apply_themes () {
        kwriteconfig5 --file kdeglobals --group "General" --key "ColorScheme" "$THEME"
        kwriteconfig5 --file kdeglobals --group "Icons" --key "Theme" "$ICONS"
        kwriteconfig5 --file kdeglobals --group "Cursor" --key "Theme" "$CURSOR"
        kwriteconfig5 --file kdeglobals --group "General" --key "font" "$FONT"
        kwriteconfig5 --file kcmfonts --group "General" --key "forceFontDPI" "0"
        kwriteconfig5 --file kcmfonts --group "General" --key "forceFontDPI" "96"
}

apply_themes

